import { useState, useRef } from "react";
import { useApp } from "../context/AppContext";
import { ROLES, bomStatusMeta } from "../constants/seeds";
import { todayStr, addDays, fmt, daysBetween } from "../utils/dateHelpers";

// ── Helpers ───────────────────────────────────────────────────────────────────
const weekRange = () => {
  const start = todayStr();
  const end   = addDays(start, 6);
  return { start, end };
};


// ── HTML report builder ───────────────────────────────────────────────────────
const buildHTML = (sections: string, title: string, user: string, dateLabel: string) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${title}</title>
<style>
  body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 760px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; background: #fff; }
  h1   { font-size: 1.5rem; color: #0a0a18; margin-bottom: 4px; }
  .meta{ font-size: 0.82rem; color: #888; margin-bottom: 28px; }
  h2   { font-size: 1rem; color: #0a0a18; margin: 24px 0 10px; padding-bottom: 5px; border-bottom: 2px solid #e5e7eb; }
  table{ width: 100%; border-collapse: collapse; font-size: 0.85rem; margin-bottom: 8px; }
  th   { background: #f3f4f6; text-align: left; padding: 6px 10px; font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.04em; color: #6b7280; }
  td   { padding: 6px 10px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .badge{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.72rem; font-weight: 600; }
  .red  { background: #fee2e2; color: #dc2626; }
  .amber{ background: #fef3c7; color: #d97706; }
  .green{ background: #d1fae5; color: #059669; }
  .blue { background: #dbeafe; color: #2563eb; }
  .grey { background: #f3f4f6; color: #6b7280; }
  .note { font-size: 0.8rem; color: #6b7280; font-style: italic; padding: 10px; background: #f9fafb; border-radius: 4px; }
  footer{ margin-top: 40px; font-size: 0.75rem; color: #d1d5db; border-top: 1px solid #f3f4f6; padding-top: 10px; }
</style>
</head>
<body>
<h1>${title}</h1>
<p class="meta">Generated ${new Date().toLocaleString("en-AU")} · ${user} · ${dateLabel}</p>
${sections}
<footer>Generated by Lattice PM</footer>
</body>
</html>`;

// ── Section components (in-app preview) ──────────────────────────────────────
const S = {
  head: (title: string) => (
    <div style={{ fontSize: "0.7rem", color: "#888", textTransform: "uppercase", letterSpacing: "0.07em", fontWeight: 600, margin: "1.25rem 0 0.6rem", paddingBottom: "5px", borderBottom: "1px solid #1e1e35" }}>
      {title}
    </div>
  ),
  empty: (msg: string) => (
    <div style={{ fontSize: "0.78rem", color: "#444", fontStyle: "italic", padding: "0.4rem 0 0.6rem" }}>{msg}</div>
  ),
  table: (cols: string[], rows: any[][], emptyMsg?: string) => (
    rows.length === 0 ? S.empty(emptyMsg || "None.") : (
      <div style={{ overflowX: "auto", marginBottom: "0.5rem" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.78rem" }}>
          <thead>
            <tr>
              {cols.map((c: string) => (
                <th key={c} style={{ textAlign: "left", padding: "0.3rem 0.6rem", fontSize: "0.62rem", color: "#444", textTransform: "uppercase", letterSpacing: "0.05em", background: "#0d0d20", borderBottom: "1px solid #1e1e35" }}>{c}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row: any[], i: number) => (
              <tr key={i}>
                {row.map((cell: any, j: number) => (
                  <td key={j} style={{ padding: "0.4rem 0.6rem", borderBottom: "1px solid #141428", color: "#ccc", verticalAlign: "top" }}>
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
  ),
};

const mapColors = { red: ["#fc818130","#fc8181"], amber: ["#f6c90e30","#f6c90e"], green: ["#48bb7830","#48bb78"], blue: ["#00d4ff30","#00d4ff"], grey: ["#55555530","#888"] } as const;

const Badge = ({ text, color }: { text: string; color: keyof typeof mapColors }) => {
  const [bg, fg] = mapColors[color] || mapColors.grey;
  return <span style={{ background: bg, color: fg, borderRadius: "4px", padding: "1px 7px", fontSize: "0.68rem", fontWeight: 600, whiteSpace: "nowrap" }}>{text}</span>;
};

// ── Main modal ────────────────────────────────────────────────────────────────
export const WeeklySummaryModal = () => {
  const { setShowSummary, currentUser, tasks, projects, users, suppliers, bom } = useApp();
  const { start, end } = weekRange();
  const now = todayStr();
  const previewRef = useRef(null);
  const [copied, setCopied] = useState(false);

  if (!currentUser) return null;
  const role = currentUser.role;
  const dateLabel = `${fmt(start)} – ${fmt(end)}`;

  // ── Shared derived data ───────────────────────────────────────────────────
  const myTasks   = role === ROLES.WORKER
    ? tasks.filter((t) => t.assigneeId === currentUser.id)
    : tasks;

  const overdue   = myTasks.filter((t) => t.endDate < now && t.status !== "done");
  const thisWeek  = myTasks.filter((t) => t.endDate >= start && t.endDate <= end && t.status !== "done");
  const doneRecent= myTasks.filter((t) => t.status === "done" && t.endDate >= addDays(now, -7));
  const blocked   = myTasks.filter((t) => t.status === "blocked");

  const overdueOrders = suppliers.flatMap((s) =>
    (s.orders || [])
      .filter((o) => !o.arrived && addDays(o.orderedDate, o.leadTimeDays) < now)
      .map((o) => ({ ...o, supplierName: s.name, dueDate: addDays(o.orderedDate, o.leadTimeDays) }))
  );
  const arrivingSoon = suppliers.flatMap((s) =>
    (s.orders || [])
      .filter((o) => { const d = addDays(o.orderedDate, o.leadTimeDays); return !o.arrived && d >= now && d <= addDays(now, 14); })
      .map((o) => ({ ...o, supplierName: s.name, dueDate: addDays(o.orderedDate, o.leadTimeDays) }))
  );

  // ── Preview sections ──────────────────────────────────────────────────────
  const getTaskRow = (t: any) => {
    const proj     = projects.find((p) => p.id === t.projectId);
    const assignee = users.find((u) => u.id === t.assigneeId);
    return [
      <span style={{ color: "#e0e0e0" }}>{t.title}</span>,
      proj ? <span style={{ color: proj.color, fontSize: "0.7rem" }}>{proj.name}</span> : "—",
      role !== ROLES.WORKER ? (assignee?.name || "—") : undefined,
      <Badge text={fmt(t.endDate)} color={t.endDate < now ? "red" : "amber"} />,
      <Badge text={t.priority} color={t.priority === "high" ? "red" : t.priority === "medium" ? "amber" : "grey"} />,
    ].filter(Boolean);
  };

  const taskCols = role !== ROLES.WORKER
    ? ["Task", "Project", "Assignee", "Due", "Priority"]
    : ["Task", "Project", "Due", "Priority"];

  // Worker view ────────────────────────────────────────────────────────────────
  const WorkerPreview = () => (
    <>
      {S.head("⚠ Overdue")}
      {S.table(taskCols, overdue.map(getTaskRow), "Nothing overdue 🎉")}

      {S.head(`📅 Due This Week (${fmt(start)} – ${fmt(end)})`)}
      {S.table(taskCols, thisWeek.map(getTaskRow), "Nothing due this week.")}

      {S.head("🔴 Blocked")}
      {S.table(taskCols, blocked.map(getTaskRow), "No blocked tasks.")}

      {S.head("✅ Completed (Last 7 Days)")}
      {S.table(taskCols, doneRecent.map(getTaskRow), "No tasks completed recently.")}
    </>
  );

  // Manager view ───────────────────────────────────────────────────────────────
  const ManagerPreview = () => {
    const projRows = projects.map((proj) => {
      const pt      = tasks.filter((t) => t.projectId === proj.id);
      const done    = pt.filter((t) => t.status === "done").length;
      const late    = pt.filter((t) => t.endDate < now && t.status !== "done").length;
      const inProg  = pt.filter((t) => t.status === "in-progress").length;
      const pct     = pt.length ? Math.round((done / pt.length) * 100) : 0;
      return [
        <span style={{ color: proj.color, fontWeight: 600 }}>{proj.name}</span>,
        `${pt.length}`,
        <Badge text={`${inProg} active`} color="blue" />,
        <Badge text={`${pct}%`} color={pct >= 75 ? "green" : pct >= 40 ? "amber" : "grey"} />,
        late > 0 ? <Badge text={`${late} late`} color="red" /> : <Badge text="On track" color="green" />,
      ];
    });

    return (
      <>
        {S.head("🗂️ Project Snapshot")}
        {S.table(["Project","Tasks","Active","Progress","Status"], projRows, "No projects.")}

        {S.head("⚠ Overdue Tasks")}
        {S.table(taskCols, overdue.map(getTaskRow), "Nothing overdue 🎉")}

        {S.head(`📅 Due This Week`)}
        {S.table(taskCols, thisWeek.map(getTaskRow), "Nothing due this week.")}

        {S.head("🔴 Blocked Tasks")}
        {S.table(taskCols, blocked.map(getTaskRow), "No blocked tasks.")}

        {S.head("📦 Overdue Deliveries")}
        {S.table(
          ["Supplier", "Order", "Was Due", "Days Late"],
          overdueOrders.map((o) => [
            o.supplierName,
            o.description,
            <Badge text={fmt(o.dueDate)} color="red" />,
            <Badge text={`${daysBetween(o.dueDate, now)}d`} color="red" />,
          ]),
          "No overdue deliveries 🎉"
        )}

        {S.head("🚚 Arriving This Fortnight")}
        {S.table(
          ["Supplier", "Order", "Expected"],
          arrivingSoon.map((o) => [o.supplierName, o.description, <Badge text={fmt(o.dueDate)} color="amber" />]),
          "No deliveries expected in the next 14 days."
        )}
      </>
    );
  };

  // Admin view ─────────────────────────────────────────────────────────────────
  const AdminPreview = () => {
    const teamRows = users.map((u) => {
      const ut   = tasks.filter((t) => t.assigneeId === u.id);
      const late = ut.filter((t) => t.endDate < now && t.status !== "done").length;
      const ip   = ut.filter((t) => t.status === "in-progress").length;
      return [
        <span style={{ color: "#e0e0e0" }}>{u.name}</span>,
        <span style={{ color: "#888", fontSize: "0.72rem", textTransform: "capitalize" }}>{u.role}</span>,
        `${ut.length}`,
        <Badge text={`${ip} active`} color="blue" />,
        late > 0 ? <Badge text={`${late} late`} color="red" /> : <Badge text="Clear" color="green" />,
      ];
    });

    const chaseRows = suppliers.flatMap((s) =>
      (s.orders || [])
        .filter((o) => !o.arrived && addDays(o.orderedDate, o.leadTimeDays) <= addDays(now, 7))
        .map((o) => {
          const due  = addDays(o.orderedDate, o.leadTimeDays);
          const late = due < now;
          return [
            s.name,
            o.description,
            <Badge text={fmt(due)} color={late ? "red" : "amber"} />,
            late ? <Badge text={`${daysBetween(due, now)}d overdue`} color="red" /> : <Badge text="Due soon" color="amber" />,
            <span style={{ fontSize: "0.7rem", color: "#555" }}>{s.contact}</span>,
          ];
        })
    );

    const pendingBom = bom.filter((b) => b.status === "pending" || b.status === "under-review").map((entry) => {
      const sup = suppliers.find((s) => s.id === entry.supplierId);
      const pt  = (sup?.parts || []).find((p) => p.id === entry.partId);
      return [
        pt?.partNumber || "—",
        pt?.description || "—",
        sup?.name || "—",
        <Badge text={bomStatusMeta[entry.status]?.label || entry.status} color={entry.status === "under-review" ? "amber" : "grey"} />,
        entry.notes ? <span style={{ fontSize: "0.7rem", color: "#666" }}>{entry.notes.slice(0, 60)}{entry.notes.length > 60 ? "…" : ""}</span> : "—",
      ];
    });

    return (
      <>
        {/* All manager sections */}
        <ManagerPreview />

        {S.head("👥 Team Workload Snapshot")}
        {S.table(["Member","Role","Tasks","Active","Status"], teamRows, "No team members.")}

        {S.head("📋 Supplier Chase List (overdue + due within 7 days)")}
        {S.table(["Supplier","Order","Due","Status","Contact"], chaseRows, "No orders need chasing right now.")}

        {S.head("🔍 BOM Items Needing Attention (Pending / Under Review)")}
        {S.table(["Part No.","Description","Supplier","Status","Notes"], pendingBom, "All BOM items are resolved.")}
      </>
    );
  };

  // ── HTML export builder ───────────────────────────────────────────────────
  const buildHTMLSections = () => {
    const row = (cells: string[]) => `<tr>${cells.map((c: string) => `<td>${c}</td>`).join("")}</tr>`;
    const thead = (cols: string[]) => `<thead><tr>${cols.map((c: string) => `<th>${c}</th>`).join("")}</tr></thead>`;
    const table = (cols: string[], rows: Array<string | string[]>): string => {
      const rowObjs = rows.map((r) => Array.isArray(r) ? r : [r]);
      return rowObjs.length === 0
        ? `<p class="note">None.</p>`
        : `<table>${thead(cols)}<tbody>${rowObjs.map(row).join("")}</tbody></table>`;
    };
    const h2 = (t: string) => `<h2>${t}</h2>`;

    const taskHTMLRow = (t: any) => {
      const proj     = projects.find((p) => p.id === t.projectId);
      const assignee = users.find((u) => u.id === t.assigneeId);
      const late = t.endDate < now;
      const cells = [
        t.title,
        proj?.name || "—",
        role !== ROLES.WORKER ? (assignee?.name || "—") : null,
        `<span class="badge ${late ? "red" : "amber"}">${fmt(t.endDate)}</span>`,
        `<span class="badge ${t.priority === "high" ? "red" : t.priority === "medium" ? "amber" : "grey"}">${t.priority}</span>`,
      ].filter(Boolean);
      return cells;
    };

    const htaskCols = role !== ROLES.WORKER
      ? ["Task","Project","Assignee","Due","Priority"]
      : ["Task","Project","Due","Priority"];

    let html = "";

    if (role === ROLES.WORKER) {
      html += h2("⚠ Overdue") + table(htaskCols, overdue.map(taskHTMLRow));
      html += h2(`📅 Due This Week (${dateLabel})`) + table(htaskCols, thisWeek.map(taskHTMLRow));
      html += h2("🔴 Blocked") + table(htaskCols, blocked.map(taskHTMLRow));
      html += h2("✅ Completed (Last 7 Days)") + table(htaskCols, doneRecent.map(taskHTMLRow));
    } else {
      // Projects snapshot
      const projHTML = projects.map((proj) => {
        const pt   = tasks.filter((t) => t.projectId === proj.id);
        const late = pt.filter((t) => t.endDate < now && t.status !== "done").length;
        const ip   = pt.filter((t) => t.status === "in-progress").length;
        const done = pt.filter((t) => t.status === "done").length;
        const pct  = pt.length ? Math.round((done / pt.length) * 100) : 0;
        return [proj.name, `${pt.length}`, `${ip} active`, `${pct}%`, late > 0 ? `<span class="badge red">${late} late</span>` : `<span class="badge green">On track</span>`];
      });
      html += h2("🗂️ Project Snapshot") + table(["Project","Tasks","Active","Progress","Status"], projHTML);
      html += h2("⚠ Overdue Tasks") + table(htaskCols, overdue.map(taskHTMLRow));
      html += h2(`📅 Due This Week (${dateLabel})`) + table(htaskCols, thisWeek.map(taskHTMLRow));
      html += h2("🔴 Blocked Tasks") + table(htaskCols, blocked.map(taskHTMLRow));
      html += h2("📦 Overdue Deliveries") + table(["Supplier","Order","Was Due","Days Late"],
        overdueOrders.map((o) => [o.supplierName, o.description, `<span class="badge red">${fmt(o.dueDate)}</span>`, `<span class="badge red">${daysBetween(o.dueDate, now)}d</span>`])
      );
      html += h2("🚚 Arriving This Fortnight") + table(["Supplier","Order","Expected"],
        arrivingSoon.map((o) => [o.supplierName, o.description, `<span class="badge amber">${fmt(o.dueDate)}</span>`])
      );

      if (role === ROLES.ADMIN) {
        const teamHTML = users.map((u) => {
          const ut   = tasks.filter((t) => t.assigneeId === u.id);
          const late = ut.filter((t) => t.endDate < now && t.status !== "done").length;
          const ip   = ut.filter((t) => t.status === "in-progress").length;
          return [u.name, u.role, `${ut.length}`, `${ip} active`, late > 0 ? `<span class="badge red">${late} late</span>` : `<span class="badge green">Clear</span>`];
        });
        html += h2("👥 Team Workload") + table(["Member","Role","Tasks","Active","Status"], teamHTML);

        const chaseHTML = suppliers.flatMap((s) =>
          (s.orders || [])
            .filter((o) => !o.arrived && addDays(o.orderedDate, o.leadTimeDays) <= addDays(now, 7))
            .map((o) => {
              const due  = addDays(o.orderedDate, o.leadTimeDays);
              const late = due < now;
              return [s.name, o.description, `<span class="badge ${late ? "red" : "amber"}">${fmt(due)}</span>`, late ? `<span class="badge red">${daysBetween(due, now)}d overdue</span>` : `<span class="badge amber">Due soon</span>`, s.contact];
            })
        );
        html += h2("📋 Supplier Chase List") + table(["Supplier","Order","Due","Status","Contact"], chaseHTML);

        const bomHTML = bom.filter((b) => b.status === "pending" || b.status === "under-review").map((entry) => {
          const sup = suppliers.find((s) => s.id === entry.supplierId);
          const pt  = (sup?.parts || []).find((p) => p.id === entry.partId);
          return [pt?.partNumber || "—", pt?.description || "—", sup?.name || "—", `<span class="badge ${entry.status === "under-review" ? "amber" : "grey"}">${bomStatusMeta[entry.status]?.label || entry.status}</span>`, entry.notes || "—"];
        });
        html += h2("🔍 BOM — Needs Attention") + table(["Part No.","Description","Supplier","Status","Notes"], bomHTML);
      }
    }

    return html;
  };

  const exportHTML = () => {
    const title = role === ROLES.WORKER
      ? `My Weekly Summary — ${currentUser.name}`
      : role === ROLES.MANAGER
      ? `Weekly Project Summary`
      : `Weekly Operations Report`;
    const html = buildHTML(buildHTMLSections(), title, currentUser.name, dateLabel);
    const blob = new Blob([html], { type: "text/html;charset=utf-8;" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href = url;
    a.download = `lattice-summary-${todayStr()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const copyText = () => {
    const lines = [];
    const addSection = (title: string, items: string[]) => {
      lines.push(`\n${title}`);
      lines.push("─".repeat(40));
      if (items.length === 0) { lines.push("  None."); return; }
      items.forEach((i: string) => lines.push(`  ${i}`));
    };

    lines.push(`◈ LATTICE PM — WEEKLY SUMMARY`);
    lines.push(`Generated: ${new Date().toLocaleString("en-AU")} · ${currentUser.name}`);
    lines.push(`Period: ${dateLabel}`);

    addSection("⚠ OVERDUE TASKS", overdue.map((t) => {
      const p = projects.find((x) => x.id === t.projectId);
      const a = users.find((x) => x.id === t.assigneeId);
      return `${t.title} [${p?.name || "?"}] due ${fmt(t.endDate)}${role !== ROLES.WORKER ? ` · ${a?.name}` : ""}`;
    }));

    addSection(`📅 DUE THIS WEEK (${dateLabel})`, thisWeek.map((t) => {
      const p = projects.find((x) => x.id === t.projectId);
      return `${t.title} [${p?.name || "?"}] due ${fmt(t.endDate)}`;
    }));

    addSection("🔴 BLOCKED", blocked.map((t) => t.title));

    if (role !== ROLES.WORKER) {
      addSection("📦 OVERDUE DELIVERIES", overdueOrders.map((o) => `${o.supplierName}: ${o.description} (due ${fmt(o.dueDate)})`));
      addSection("🚚 ARRIVING SOON", arrivingSoon.map((o) => `${o.supplierName}: ${o.description} (expected ${fmt(o.dueDate)})`));
    }

    if (role === ROLES.ADMIN) {
      const chase = suppliers.flatMap((s) =>
        (s.orders || [])
          .filter((o) => !o.arrived && addDays(o.orderedDate, o.leadTimeDays) <= addDays(now, 7))
          .map((o) => `${s.name}: ${o.description} — ${s.contact}`)
      );
      addSection("📋 SUPPLIER CHASE LIST", chase);
    }

    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  const roleLabel = { admin: "Admin Report", manager: "Manager Report", worker: "Personal Summary" }[role];

  return (
    <div
      onClick={() => setShowSummary(false)}
      style={{ position: "fixed", inset: 0, background: "rgba(0,0,0,0.85)", zIndex: 1000, display: "flex", alignItems: "flex-start", justifyContent: "center", padding: "1.5rem 1rem", overflowY: "auto" }}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{ background: "#0f0f1e", border: "1px solid #252540", borderRadius: "14px", width: "100%", maxWidth: "760px", marginBottom: "1.5rem" }}
      >
        {/* Header */}
        <div style={{ padding: "1.25rem 1.5rem", borderBottom: "1px solid #1e1e35", display: "flex", alignItems: "center", justifyContent: "space-between", gap: "1rem", flexWrap: "wrap" }}>
          <div>
            <h2 style={{ fontFamily: "'Playfair Display',serif", fontSize: "1.2rem", color: "#e0e0e0" }}>📊 Weekly Summary</h2>
            <div style={{ fontSize: "0.75rem", color: "#555", marginTop: "3px" }}>
              {dateLabel} · {currentUser.name} · <span style={{ color: "#00d4ff" }}>{roleLabel}</span>
            </div>
          </div>
          <div style={{ display: "flex", gap: "0.5rem", flexWrap: "wrap" }}>
            <button
              onClick={copyText}
              style={{ padding: "0.4rem 0.9rem", background: copied ? "#48bb7818" : "#15152a", border: `1px solid ${copied ? "#48bb78" : "#252540"}`, borderRadius: "6px", color: copied ? "#48bb78" : "#888", fontSize: "0.78rem", cursor: "pointer", transition: "all 0.2s" }}
            >
              {copied ? "✓ Copied!" : "📋 Copy Text"}
            </button>
            <button
              onClick={exportHTML}
              style={{ padding: "0.4rem 0.9rem", background: "#00d4ff18", border: "1px solid #00d4ff50", borderRadius: "6px", color: "#00d4ff", fontSize: "0.78rem", cursor: "pointer" }}
            >
              ⬇ Export HTML
            </button>
            <button
              onClick={() => setShowSummary(false)}
              style={{ padding: "0.4rem 0.75rem", background: "transparent", border: "1px solid #252540", borderRadius: "6px", color: "#555", fontSize: "0.78rem", cursor: "pointer" }}
            >
              ✕ Close
            </button>
          </div>
        </div>
        {/* Summary stats pills */}
        <div style={{ display: "flex", gap: "0.6rem", padding: "0.9rem 1.5rem", borderBottom: "1px solid #141428", flexWrap: "wrap" }}>
          {([
            [overdue.length,       "Overdue",    overdue.length > 0       ? "#fc8181" : "#48bb78"] as const,
            [thisWeek.length,      "Due This Week", "#f6c90e"] as const,
            [blocked.length,       "Blocked",    blocked.length > 0       ? "#fc8181" : "#888"] as const,
            [doneRecent.length,    "Done Recently", "#48bb78"] as const,
            ...(role !== ROLES.WORKER ? [[overdueOrders.length, "Late Deliveries", overdueOrders.length > 0 ? "#fc8181" : "#48bb78"] as const] : []),
          ] as const).map(([val, label, color]) => (
            <div key={label} style={{ background: "#15152a", border: "1px solid #1e1e35", borderRadius: "8px", padding: "0.4rem 0.85rem", display: "flex", alignItems: "center", gap: "0.45rem" }}>
              <span style={{ fontSize: "1rem", fontWeight: 700, color }}>{val}</span>
              <span style={{ fontSize: "0.68rem", color: "#555" }}>{label}</span>
            </div>
          ))}
        </div>

        {/* Report body */}
        <div ref={previewRef} style={{ padding: "0.75rem 1.5rem 1.5rem" }}>
          {role === ROLES.WORKER  && <WorkerPreview />}
          {role === ROLES.MANAGER && <ManagerPreview />}
          {role === ROLES.ADMIN   && <AdminPreview />}
        </div>
      </div>
    </div>
  );
};
